# SPDX-FileCopyrightText: 2026 Stefan Riesenberger <stefan.riesenberger@gmail.com>
# SPDX-License-Identifier: GPL-2.0-or-later

[Device]
name=Fairphone 5

[Panels]
statusBarHeight=106
leftPadding=15
rightPadding=15

[Panels][Top]
centerSpacing=86
