# SPDX-FileCopyrightText: 2025 John Ericson <john@snurr.nu>
# SPDX-License-Identifier: GPL-2.0-or-later

[Device]
name=OnePlus 6T

[Panels]
leftPadding=16
rightPadding=16

[Panels][Top]
centerSpacing=32
