# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kauth': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kpackage': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/modemmanager-qt': 'Frameworks/6.24'
    'frameworks/networkmanager-qt': 'Frameworks/6.24'
    'frameworks/kjobwidgets': 'Frameworks/6.24'
    'plasma/kwayland': '@same'
    'plasma/libkscreen': '@same'
    'plasma/libplasma': '@same'
    'plasma/kwin': '@same'
    'plasma/plasma-workspace': '@same'
    'libraries/kirigami-addons': 'v1.11.0'
Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
 run-qmllint: true

RuntimeDependencies:
 - 'on': ['Linux']
   'require':
    'plasma/plasma-nm': '@same'
    'plasma/plasma-pa': '@same'
    'plasma/bluedevil': '@same'
    'plasma/milou': '@same'
    'plasma/qqc2-breeze-style': '@same'
    'frameworks/bluez-qt': 'Frameworks/6.24'
 - 'on': ['Linux', 'FreeBSD']
   'require':
    'plasma/milou': '@same'
