[Desktop Entry]
Encoding=UTF-8
Exec=dbus-launch --exit-with-session ${CMAKE_INSTALL_FULL_BINDIR}/startplasmacompositor
TryExec=${CMAKE_INSTALL_FULL_BINDIR}/startplasmacompositor
DesktopNames=KDE
Name=Plasma Mobile
Name[ast]=Plasma Mobile
Name[ca]=Plasma Mòbil
Name[ca@valencia]=Plasma Mòbil
Name[en_GB]=Plasma Mobile
Name[es]=Plasma Mobile
Name[gl]=Plasma Mobile
Name[nl]=Plasma-mobiel
Name[nn]=Plasma Mobile
Name[pl]=Plazma Mobile
Name[pt]=Plasma Mobile
Name[sv]=Plasma mobil
Name[uk]=Мобільна Плазма
Name[x-test]=xxPlasma Mobilexx
Name[zh_TW]=Plasma 行動
Comment=Plasma Mobile by KDE
Comment[ast]=Plasma Mobile por KDE
Comment[ca]=Plasma Mòbil, creat per la comunitat KDE
Comment[ca@valencia]=Plasma Mòbil, creat per la comunitat KDE
Comment[en_GB]=Plasma Mobile by KDE
Comment[es]=Plasma Mobile creado por KDE
Comment[gl]=Plasma Mobile de KDE
Comment[nl]=Plasma-mobiel door KDE
Comment[nn]=Plasma Mobile frå KDE
Comment[pl]=Plazma Mobile stworzona przez KDE
Comment[pt]=Plasma Mobile do KDE
Comment[sv]=Plasma mobil av KDE
Comment[uk]=Мобільна Плазма від KDE
Comment[x-test]=xxPlasma Mobile by KDExx
Comment[zh_TW]=來自 KDE 的 Plasma 行動作業系統
